### ISSUE TITLE
vegalite no longer working with pandas 1.0 or later version

### ISSUE THREAD

**Issue by kcdoo** [vega/ipyvega#203]
https://github.com/vega/ipyvega/blob/004e0ded003e2d46d880205012c81c639cd13d8c/vega/utils.py#L41

I'm calling VegaLite(vega_bar, display_df)
I get the error:
AttributeError: module 'pandas.core' has no attribute 'index'

Looks like pandas.core.index has been deprecated

I think the fix can be done in vega/utils.py (the link above) similar to this fix.
https://github.com/quantopian/qgrid/issues/287

I'm happy to try to fix myself, but not so confident.  I love vega though.  Thanks!

here is most of the stack trace:
    172         if display_df is not None:
--> 173             display(VegaLite(vega_bar, display_df))
    174         else:
    175             print("   No histogram data return for this field. ")

~/anaconda3/lib/python3.7/site-packages/vega/base.py in __init__(self, spec, data, opt)
     20         spec = spec
     21         self.opt = opt or {}
---> 22         self.spec = self._prepare_spec(spec, data)
     23 
     24     def _prepare_spec(self, spec, data):

~/anaconda3/lib/python3.7/site-packages/vega/vegalite.py in _prepare_spec(self, spec, data)
     11 
     12     def _prepare_spec(self, spec, data):
---> 13         return prepare_spec(spec, data)
     14 
     15 

~/anaconda3/lib/python3.7/site-packages/vega/utils.py in prepare_spec(spec, data)
     93         # We have to do the isinstance test first because we can't
     94         # compare a DataFrame to None.
---> 95         data = sanitize_dataframe(data)
     96         spec['data'] = {'values': data.to_dict(orient='records')}
     97     elif data is None:

~/anaconda3/lib/python3.7/site-packages/vega/utils.py in sanitize_dataframe(df)
     39     df = df.copy()
     40 
---> 41     if isinstance(df.index, pd.core.index.MultiIndex):
     42         raise ValueError('Hierarchical indices not supported')
     43     if isinstance(df.columns, pd.core.index.MultiIndex):

AttributeError: module 'pandas.core' has no attribute 'index'

**Comment by domoritz** [comment]
Thanks for filing the issue. Can you send a pull request to fix it?

**Comment by kcdoo** [comment]
I'll try, but no promises.  :)

**Comment by domoritz** [comment]
Thank you. I will take care of it eventually but it might take some time.

**Comment by kcdoo** [comment]
I tried to fix this, but I could not duplicate the error.  Turns out it is working with the latest version of vega and I just needed to upgrade from 2.6.0 to 3+.  Sorry for the bother.  It is working great now.

**Comment by uli22** [comment]
I managed to overcome the issue with this post: https://github.com/python-visualization/folium/issues/1239
While I can display a histogram in a popup of a marker it seems not to be possible to attach them to tooltips, resp. by  folium.features.GeoJsonTooltip or folium.features.GeoJsonPopup

**Comment by domoritz** [comment]
@uli22 are you saying there is an issue or not? I don't seem to be having issues with Pandas 1.
